version: '3.8'
services:
  database:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - 33066:3306
  app:
    working_dir: /usr/src/app
    build: ./docker/app
    command: npm run start:dev --trace-warning
    ports:
      - 3420:3420
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: app
      DB_USER: root
      DB_PASSWORD: root
